### ISSUE TITLE
Updating trainable lemmatizer

### ISSUE THREAD

**Issue by Premshay** [jmyerston/greCy#3]
It's great that you've added the trainable lemmatizer. With the previous version I added my own trainable lemmatizer and it helped improve lemmatization.
I now want to update your trainable lemmatizer with my data, but I've encountered 2 issues with that:

1. I have my own config, with pipe components sourced to yours. when doing debug data on my config I get the following error from the trainable lemmatizer component:
```
`Output exceeds the [size limit](command:workbench.action.openSettings?%5B%22notebook.output.textLineLimit%22%5D). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?6a9a33ea-8812-493f-8c8e-ed9c05854774)
Traceback (most recent call last):
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\huggingface_hub\utils\_errors.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/huggingface_hub/utils/_errors.py)", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\requests\models.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/requests/models.py)", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/transformer/resolve/main/tokenizer_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\transformers\utils\hub.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/transformers/utils/hub.py)", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\huggingface_hub\utils\_validators.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/huggingface_hub/utils/_validators.py)", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\huggingface_hub\file_download.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/huggingface_hub/file_download.py)", line 1160, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\huggingface_hub\utils\_validators.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/huggingface_hub/utils/_validators.py)", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\huggingface_hub\file_download.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/huggingface_hub/file_download.py)", line 1501, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\huggingface_hub\utils\_errors.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/huggingface_hub/utils/_errors.py)", line 291, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64198c2e-4010f5b839ca08691d3fe261)

Repository Not Found for url: https://huggingface.co/transformer/resolve/main/tokenizer_config.json.
...
  File "[j:\Anaconda3\envs\nlp\lib\site-packages\transformers\utils\hub.py](file:///J:/Anaconda3/envs/nlp/lib/site-packages/transformers/utils/hub.py)", line 424, in cached_file
    raise EnvironmentError(
OSError: transformer is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True.`
```
I think k it's related to the trainable lemmatizer tok2vec on your config: spacy-transformers.Tok2VecTransformer.v3

2. Do you know of a way to update the lemmatizer, instead of training from scratch? I'm trying to do it using the [updater](https://spacy.io/api/edittreelemmatizer#update), but it doesn't seem to work as well; when I try to initialize the grc_ud_proiel_trf pipeline (optimizer = nlp.initialize()) I get the following error:
`ValueError: Can't read file: data\augments\attribute_ruler_patterns.json`
This, by the way, is also a reason why I can't add your initialization code to my own config.

Do you know how to solve any of these issues?

**Comment by jmyerston** [comment]
If you add new data it is better to train the lemmatizer from scratch.  Without seeing your config file, it is hard to tell what the error with the attribute ruler is.
